### ISSUE TITLE
PCSX2 ABI Break

### ISSUE THREAD

**Issue by StephDC** [AOSC-Dev/aosc-os-abbs#1384]
Bug description
-----------------------

PCSX2 C++ ABI Break - Version mismatch

Reproducing steps
---------------------------

```
$ PCSX2
Fatal Error: Mismatch between the program and library build versions detected.
The library used 3.0 (wchar_t,compiler with C++ ABI 1010,wx containers,compatible with 2.8),
and your program used 3.0 (wchar_t,compiler with C++ ABI 1009,wx containers,compatible with 2.8).
已經終止 (核心已傾印)
```

Update channel(s)
--------------------------

Stable

Package and version
------------------------------

`pcsx2/stable,now 1.4.0 amd64 [已安装]`

**Comment by MingcongBai** [comment]
Fixed with:

- PCSX2 rebuild and build configuration clean-up: https://github.com/AOSC-Dev/aosc-os-abbs/commit/d592925931f48c7c5b241faaf4dcee3ab62bbc43
- WxGTK+ update, and removing ABI check as fatal error: https://github.com/AOSC-Dev/aosc-os-abbs/commit/bf3e106f77e5053300105d29355080f882dfbbaf

Closing.
