### ISSUE TITLE
pakreq: oregano

### ISSUE THREAD

**Issue by bobcao3** [AOSC-Dev/aosc-os-abbs#192]
Qucs & Oregano
Scientific software
Used for design & simulate electrical circuits

**Comment by Icenowy** [comment]
I have already added Qucs.

- 发送自我的Sony Xperia™智能手机

---- Bob Cao编写 ----

Qucs & Oregano
Scientific software
Used for design & simulate electrical circuits

---
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/AOSC-Dev/aosc-os-abbs/issues/192

**Comment by bobcao3** [comment]
神速

**Comment by Icenowy** [comment]
It's in it last Saturday

- 发送自我的Sony Xperia™智能手机

---- Bob Cao编写 ----

神速


---
