### ISSUE TITLE
RFC: drop armel support

### ISSUE THREAD

**Issue by eatradish** [AOSC-Dev/aosc-os-abbs#1974]
Considering that the current community interest in armel is lower than the Retro branch, it is difficult to maintain, we should drop armel support

**Comment by sztsian** [comment]
I tend to agree that armv7 is probably not as high priority as aarch64, but I think it is not so bad (far from the 'bad to keep')

**Comment by KexyBiscuit** [comment]
## Motivation

I personally closed the [security issue of VLC](https://github.com/AOSC-Dev/aosc-os-abbs/issues/1973#issuecomment-523846442), since VLC has been FTBFS for a while on Armv7-A but works fine on all other 4 arches receiving security updates routinely. Currently, the build agent available for Armv7-A is [NVIDIA Jetson TX1 Developer Kit](https://developer.nvidia.com/embedded/jetson-tx1-developer-kit), whose processor is [Quad-core ARM® Cortex®-A57 MPCore](https://www.arm.com/products/silicon-ip-cpu/cortex-a/cortex-a57) [r1p1](https://developer.arm.com/docs/ddi0488/latest/introduction/product-revisions), which is a little bit old. This may affect the [building results](https://github.com/AOSC-Dev/aosc-os-abbs/issues/1960), causing vendor lock-in.

**Comment by MingcongBai** [comment]
I am against this - we should not justify dropping a port simply because a build host is exhibiting runtime issues (as described by @KexyBiscuit ).

@Icenowy Has suggested that we started stripping features from `armel` packages, however.

**Comment by MingcongBai** [comment]
ARMv7 is now a Retro port, with limited maintenance. Closing.
