### ISSUE TITLE
Standard "xterm" alternatives?

### ISSUE THREAD

**Issue by MingcongBai** [AOSC-Dev/aosc-os-abbs#28]
Some packages like `steam` and `winff` will need `xterm` to provide terminal emulation support, should we provide a virtual package for `xterm` and an alternative to link to this executable?

**Comment by Arthur2e5** [comment]
I have read a list of xterm replacements [here](http://www.reddit.com/r/linux/comments/1k57a5/xterm_replacement_so_many_alternatives_but_which), but I am quite unsure about how those programs with xterm-like options will act when they find an option not supported by them but supported by xterm.

BTW most people would be actually more happy to see their DE's terminal emulator actually running. That would be a tough task for us, since we need to parse, discard and translate the non-getopts-style args.

**Comment by MingcongBai** [comment]
Wow, Reddit.

Debian has `x-terminal` or something standard, I will grab a copy of Debian tonight and see how it works with Steam.

**Comment by Arthur2e5** [comment]
A late update: `getopt`(1) has a `-a` arg to use the `-alternative` style.

**Comment by Arthur2e5** [comment]
I took a look on the Debian patched Konsole. They added a dummy `-T` option to let it directly basically fake `xterm`.. Interesting approach.

Maybe they have a list of options that defines a basic `x-terminal-emulator`.

**Comment by MingcongBai** [comment]
Simply patching a terminal emulator sounds just silly for the purpose... But I don't have anything against it anyways...

**Comment by MingcongBai** [comment]
Stalled (feature/design change) issue, closing. Please open a new issue if this thought arises again.
