### ISSUE TITLE
deleted

### ISSUE THREAD

**Issue by broncotc** [AOSC-Dev/aosc-os-abbs#335]
deleted

**Comment by KexyBiscuit** [comment]
Wondering what's the license of it?

**Comment by KexyBiscuit** [comment]
Not sure why didn't I see it.
> Hentai@Home is an Open Source project released under the GNU General Public Licence v3.
https://e-hentai.org/hentaiathome.php (Login required)

**Comment by Artoria2e5** [comment]
Current bin (jar) is at https://repo.e-hentai.org/hath/HentaiAtHome_1.6.1.zip; src is at https://repo.e-hentai.org/hath/HentaiAtHome_1.6.1_src.zip. No auth needed.

Might need a systemd unit for autostart, since they really care about uptime. Or just do the `screen` thing.

Claims need for java 8 through 11. Might be a fun thing to figure out why.
