### ISSUE TITLE
pakreq: Android Studio

### ISSUE THREAD

**Issue by LionNatsu** [AOSC-Dev/aosc-os-abbs#392]
The Official IDE for Android.

https://developer.android.com/studio/index.html

**Comment by cthbleachbit** [comment]
Not recommended. Android studio will attempt to install it's own updates and Android SDK to its own folder.

**Comment by LionNatsu** [comment]
@cthbleachbit Is there any way to stop this? Compiling options or …?

**Comment by MingcongBai** [comment]
> @cthbleachbit Is there any way to stop this? Compiling options or …?

It's not exactly open source is it...

**Comment by MingcongBai** [comment]
Also by design, it installs all SDK files to its own installation directory, which could potentially be `/usr/lib/android-studio` (if we were going to package this).

I have just checked Ubuntu's PPA which provides Android Studio, they have simply `chmod 777` the installation directory, which I simply couldn't bring myself to do.

**Comment by LionNatsu** [comment]
> Also by design, it installs all SDK files to its own installation directory, which could potentially be /usr/lib/android-studio (if we were going to package this).

How about a group to provide such a permission?

**Comment by MingcongBai** [comment]
> How about a group to provide such a permission?

Installing oneself might just be easier...

**Comment by MingcongBai** [comment]
Closing: not suitable for packaged installation.
