### ISSUE TITLE
gpg: development version packed

### ISSUE THREAD

**Issue by lmy441900** [AOSC-Dev/aosc-os-abbs#529]
```
lmy441900@junde-hp-g6 [ ~ ] $ LANG=C gpg --version
gpg (GnuPG) 2.1.16-unknown
libgcrypt 1.7.3
NOTE: THIS IS A DEVELOPMENT VERSION!
It is only intended for test purposes and should NOT be
used in a production environment or with production keys!
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Home: /home/lmy441900/.gnupg
Supported algorithms:
Pubkey: RSA, ELG, DSA, ECDH, ECDSA, EDDSA
Cipher: IDEA, 3DES, CAST5, BLOWFISH, AES, AES192, AES256, TWOFISH,
        CAMELLIA128, CAMELLIA192, CAMELLIA256
Hash: SHA1, RIPEMD160, SHA256, SHA384, SHA512, SHA224
Compression: Uncompressed, ZIP, ZLIB, BZIP2
```

**Comment by lmy441900** [comment]
May be packed in 011b308.

**Comment by MingcongBai** [comment]
It always had been since we are using the 2.1 branch, so is Arch Linux and the upcoming Debian Jessie (testing at the moment)... And version 7.9 of Linux From Scratch.

To be fair though, I must admit that I wasn't thinking much about the consequence **or** the implication of choosing the 2.1 branch over 1.4/2.0... Maybe this "What's new" link could provide you with some information:

https://www.gnupg.org/faq/whats-new-in-2.1.html

But all in all... Although I did not make the "conscious" (so to speak) decision on the branch choice, I am fairly confident that this choice was, is, and will be supported in the forseeable future.

**Comment by Artoria2e5** [comment]
I don't think anyone want to build a version of GnuPG without ECC. I am pretty fine with it as long as it's tagged with a version number like LibreOffice Fresh.

**Comment by lmy441900** [comment]
No...

I mean, **there are no such prompt before.***

**Comment by MingcongBai** [comment]
Couldn't find any reference in the patches introduced... Are you sure the prompt wasn't there before?

**Comment by lmy441900** [comment]
@MingcongBai I AM SURE.

**Comment by MingcongBai** [comment]
@lmy441900 Darn.

**Comment by lmy441900** [comment]
This prompt is just like "insecure memory"; it is printed before any operation.

**Comment by Artoria2e5** [comment]
I have seen it in an android gpg 2.1 build too. Well since it wasn't there even if we were using 2.1, we must have messed up some build environment specs...

**Comment by MingcongBai** [comment]
Would you mind checking over the patches again?


在 2016年12月21日 22:49, Mingye Wang 写道:

**Comment by lmy441900** [comment]
It is not showing up now. Closing.
