### ISSUE TITLE
git, subversion, mercurial, cvs: arbitrary code execution on client side with crafted urls

### ISSUE THREAD

**Issue by cthbleachbit** [AOSC-Dev/aosc-os-abbs#693]
### git
* CVE-2017-1000117
* Ref: https://lkml.org/lkml/2017/8/10/757
* Upgrading to 2.13.5

### subversion
* CVE-2017-9800
* Ref: http://subversion.apache.org/security/CVE-2017-9800-advisory.txt
* Upgrading to 1.9.7

### mercurial
* CVE-2017-1000115
* CVE-2017-1000116
* Ref: https://www.mercurial-scm.org/pipermail/mercurial/2017-August/050522.html
* Upgrading to 4.2.3

**Comment by cthbleachbit** [comment]
Just fixed a typo in issue text (along with the CVEs). Closing.

**Comment by l2dy** [comment]
http://lists.nongnu.org/archive/html/bug-cvs/2017-08/msg00000.html

> CVS has a similar problem with the -d option:

Is CVE-2017-12836 fixed?

**Comment by lmy441900** [comment]
@l2dy 

> Is CVE-2017-12836 fixed?

Probably not yet.

**Comment by lmy441900** [comment]
@l2dy 

Just now I tested our `cvs` with reproducer retrieved from https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2017-12836.

Well, I received a bunch of `*** %n in writable segment detected ***` (this is because `-D_FORTIFY_SOURCE=2` is in use). This indicates:

1. Our `cvs` is broken, and needs to be fixed;
2. Our `cvs` is immune from this issue.

Though this sounds somewhat ridiculous, but we will plan to fix `cvs` on our `staging` branch instead of `bugfix` branch.

**Comment by lmy441900** [comment]
> but we will plan to fix cvs on our staging branch instead of bugfix branch.

Or (to disambiguate), we will first have a discussion on how to solve this issue... and not regarding it as an urgent security one.

**Comment by l2dy** [comment]
That's fine because

> Of course, the repo specification looks very odd, so tricking a victim
may be harder than for SCM tools where it's prefixed by an ssh://, or
masked behind a redirect, or submodule paths may be followed without
user interaction.

**Comment by MingcongBai** [comment]
What is the state of this issue after the patch referenced above? @lmy441900

**Comment by l2dy** [comment]
- AOSA-2017-0057: Update Git to 2.13.5 (CVE-2017-1000117).
- AOSA-2017-0058: Update Subversion to 1.9.7 (CVE-2017-9800).
- AOSA-2017-0059: Update Mercurial to 4.2.3 (CVE-2017-1000115, CVE-2017-1000116).
- AOSA-2017-0095: Fix CVE-2017-12836 in CVS.
