### ISSUE TITLE
blender: rebuild needed

### ISSUE THREAD

**Issue by lmy441900** [AOSC-Dev/aosc-os-abbs#915]
```
lmy441900@junde-dell-vostro [ ~ ] $ blender
blender: error while loading shared libraries: libopencv_videoio.so.3.1: cannot open shared object file: No such file or directory
```

**Comment by lmy441900** [comment]
```
lmy441900@junde-dell-vostro [ ~ ] ? dpkg -S libopencv_videoio.so
opencv: /usr/lib/libopencv_videoio.so.3.3
opencv: /usr/lib/libopencv_videoio.so
opencv: /usr/lib/libopencv_videoio.so.3.3.0
```

**Comment by cthbleachbit** [comment]
Acknowledged.

On Dec 27, 2017 4:23 PM, "Junde Yhi" <notifications@github.com> wrote:

lmy441900@junde-dell-vostro [ ~ ] ? dpkg -S libopencv_videoio.so
opencv: /usr/lib/libopencv_videoio.so.3.3
opencv: /usr/lib/libopencv_videoio.so
opencv: /usr/lib/libopencv_videoio.so.3.3.0

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/AOSC-Dev/aosc-os-abbs/issues/915#issuecomment-354074313>,
or mute the thread

**Comment by cthbleachbit** [comment]
Which release channel you are on? Bugfix? Testing?

**Comment by lmy441900** [comment]
> Which release channel you are on? Bugfix? Testing?

Bugfix (Stable).

**Comment by MingcongBai** [comment]
Testing has this fix and I'll make sure it ships tomorrow, we were encountering build failures from the last cycle - just to complete the context with @cthbleachbit 's question. Sorry.
