### ISSUE TITLE
mupdf: CVE-2017-17858

### ISSUE THREAD

**Issue by l2dy** [AOSC-Dev/aosc-os-abbs#981]
https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2017-17858

**Comment by MingcongBai** [comment]
We are currently on 1.11 branch, though staging should go on 1.12 soon - marking `to-staging`.

**Comment by l2dy** [comment]
No AOSA then.

**Comment by MingcongBai** [comment]
Well not yet, until we merge the next staging round.

**Comment by l2dy** [comment]
If we can't reproduce https://github.com/mzet-/Security-Advisories/blob/master/mzet-adv-2017-01.md with our current version and fix it while updating mupdf, no AOSA should be assigned. Correct?

**Comment by l2dy** [comment]
https://security-tracker.debian.org/tracker/CVE-2017-17858
>mupdf <not-affected> (Vulnerable code introduced in 1.11.1)

We were at 1.11, so no AOSA.

**Comment by MingcongBai** [comment]
However...

"Heap-based buffer overflow in the ensure_solid_xref function in pdf/pdf-xref.c in Artifex MuPDF 1.12.0 allows a remote attacker to potentially execute arbitrary code via a crafted PDF file, because xref subsection object numbers are unrestricted. "

And fixes has been introduced as part of the 1.12 branch - I thought that should qualify for an AOSA?

**Comment by l2dy** [comment]
This is the "we were never affected" case. Patch for this issue was included when the package was updated.
